name: Build Docker Images

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Freeing up build space
        run: |
          # https://github.com/apache/flink/blob/b8f8d6e602897b7f275f1db36478f5e8f1d6604e/tools/azure-pipelines/free_disk_space.sh

          echo "=============================================================================="
          echo "Freeing up disk space on CI system"
          echo "=============================================================================="

          echo "Listing 100 largest packages"
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          df -h
          echo "Removing large packages"
          sudo apt-get remove -y '^dotnet-.*' || true
          sudo apt-get remove -y '^llvm-.*' || true
          sudo apt-get remove -y 'php.*' || true
          sudo apt-get remove -y '^mongodb-.*' || true
          sudo apt-get remove -y '^mysql-.*' || true
          sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri || true
          sudo apt-get remove -y build-essential || true
          sudo apt-get autoremove -y || true
          sudo apt-get clean || true
          df -h
          echo "Removing large directories"

          sudo rm -rf /usr/share/dotnet/ || true
          sudo rm -rf /usr/local/graalvm/ || true
          sudo rm -rf /usr/local/.ghcup/ || true
          sudo rm -rf /usr/local/share/powershell || true
          sudo rm -rf /usr/local/share/chromium || true
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/local/lib/node_modules || true
          df -h

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base image
        uses: docker/build-push-action@v6
        with:
          tags: pan93412/musetalk:1.5-base
          file: Dockerfile.base
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Gradle image
        uses: docker/build-push-action@v6
        with:
          tags: pan93412/musetalk:1.5-gradle
          file: Dockerfile
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ secrets.GITHUB_TOKEN }}
